### ISSUE TITLE
hi,can u explain how to use?

### ISSUE THREAD

**Issue by guzuomuse** [jhell96/Fabricjs-responsive#1]
thanks~~

**Comment by jhell96** [comment]
I built this out a while back -- I don't think I updated with my final code (so it's just a starting point).

However:
The public/app/annotator.js contains the js code for making fabric responsive to screen size (it should scale the fabric objects if I remember correctly). public/index.html contains code for a basic fabric canvas. 

It's not currently set up to be downloaded/cloned, but you can simply copy the annotator.js file and reference that js code in any html file. It is set up so that the fabric canvas has the id="annotator". Should resize everything according to the screen.

**Comment by guzuomuse** [comment]
got it, i have checked the source code...thank you...
